name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '19'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i 'd:/personal-project/discord-clone-docs/chatcord-key-pair.pem' ubuntu@13.215.48.21 'cd /home/ubuntu/discord-clone && git pull && npm install && npm run build'

      # - name: Deploy to AWS
      #   uses: easingthemes/aws-elasticbeanstalk-deploy@v3
      #   with:
      #     access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     region: your-aws-region
      #     application_name: your-application-name
      #     environment_name: your-environment-name
      #     zip_file: build.zip
